Allow setting user_verification in settings
CZ-NIC/django-fido pull request #195
Opened 2022-12-15 02:06 UTC by variable

Resolves https://github.com/CZ-NIC/django-fido/issues/193

2022-12-20 08:28 UTC, tpazderka requested changes
Changelog entry is missing.

2022-12-20 08:28 UTC, tpazderka commented on README.md
> +Set 'DJANGO_FIDO_USER_VERIFICATION' to 'required',  'preferred' or 'discouraged', default is None
Please use backticks "`".

2022-12-22 02:19 UTC, variable commented on README.md
> +Set 'DJANGO_FIDO_USER_VERIFICATION' to 'required',  'preferred' or 'discouraged', default is None
updated, thanks

2023-01-11 07:49 UTC, tpazderka approved these changes

2023-01-19 15:07 UTC, merged